### PR TITLE
update the path for virtual hosted, signv2 and add tests

### PR DESCRIPTION
**Pull request by BrennaEpp**
Also strips scheme for the emulator host if present

### CODE REVIEW

**Comment by BrennaEpp** [comment]
Hi @ChrisBr, are you able/willing to review these changes? If not, I can open a PR directly against googleapis/google-cloud-go as long as you sign the CLA.

**Review by ChrisBr — APPROVED** [review]

**Comment by ChrisBr** [comment]
✅ @BrennaEpp

**Comment by ChrisBr** [comment]
Should I still sign the CLA?

**Comment by BrennaEpp** [comment]
Yes please @ChrisBr .
You can sign it at https://cla.developers.google.com/

**Pull request closed without merging**
